/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/item/ArticleItem.vue')['default']
    ArticleList: typeof import('./src/components/list/load/ArticleList.vue')['default']
    AuthBtn: typeof import('./src/components/common/AuthBtn/index.vue')['default']
    FollowBtn: typeof import('./src/components/common/FollowBtn/index.vue')['default']
    ImgPreview: typeof import('./src/components/common/ImgPreview/index.vue')['default']
    Logo: typeof import('./src/components/common/Logo/index.vue')['default']
    Message: typeof import('./src/components/modal/message/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserData: typeof import('./src/components/common/UserData/index.vue')['default']
    UserViews: typeof import('./src/components/common/UserViews/index.vue')['default']
  }
}
